name: chembed
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.8
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anthropic==0.21.3
    - anyio==4.3.0
    - attrs==23.2.0
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - datasets==2.18.0
    - dill==0.3.8
    - distro==1.9.0
    - eval-type-backport==0.1.3
    - filelock==3.13.1
    - fonttools==4.49.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - h11==0.14.0
    - httpcore==1.0.4
    - httpx==0.27.0
    - huggingface-hub==0.21.4
    - idna==3.6
    - jinja2==3.1.3
    - joblib==1.3.2
    - jsonlines==4.0.0
    - kiwisolver==1.4.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.8.3
    - mdurl==0.1.2
    - mpmath==1.2.1
    - mteb==1.3.2
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.2.1
    - numpy==1.26.4
    - openai==1.14.3
    - packaging==24.0
    - pandas==2.2.1
    - pillow==9.3.0
    - pyarrow==15.0.1
    - pyarrow-hotfix==0.6
    - pydantic==2.6.4
    - pydantic-core==2.16.3
    - pygments==2.17.2
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytrec-eval==0.5
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.31.0
    - rich==13.7.1
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - sentence-transformers==2.5.1
    - six==1.16.0
    - sniffio==1.3.1
    - sympy==1.12
    - threadpoolctl==3.3.0
    - tokenizers==0.15.2
    - torch==2.3.0.dev20240310
    - torchaudio==2.2.0.dev20240310
    - torchvision==0.18.0.dev20240310
    - tqdm==4.66.2
    - transformers==4.38.2
    - typing-extensions==4.8.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - xxhash==3.4.1
    - yarl==1.9.4
prefix: /opt/anaconda3/envs/chembed
